== Camel Example Spring Boot MitchConnect

This example shows how to receive and forward SSL encrypted
messages via MLLP. It logs the messages to a SQLite database
in its toplevel directory, so SQLite must be installed.

Once you see the "Completed initialization in x ms" message,
you can point a web browser to localhost:8080/api/routes
to see the loaded routes, and to localhost:8080/api/routes/load
to load a valid yaml file route
or enter valid yaml to create a route.

If the entered yaml is not valid it will not load but there
will be no message.  If it is valid you will see it when
your browser is redirected to /api/routes.

You can Stop and Suspend routes.  Stopped or suspended routes
can be Started.

The application.yaml file is in src/main/resources, and keystore
and truststore and port information is under camel: mllp: ssl:


=== How to run

You can run this example using

    mvn spring-boot:run

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/support.html[let us know].

We also love contributors, so
https://camel.apache.org/contributing.html[get involved] :-)

The Camel riders!



