#logging:
#  level:
#    org.apache.camel.component.mllp: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - "prometheus"
          - "camelroutes"
          - "metrics"

spring:
  dataSource:
    url: jdbc:sqlite:mydata.db
    driver-class-name: org.sqlite.JDBC
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    mode: "HTML"
    encoding: "UTF-8"
    
camel:
  management:
    enabled: true
    jmxAgent: true
    
  micrometer:
    enabled: true
    route-metrics: true
  netty:
    ssl:
      keystore:
        password: "password"
        resource: file:/Users/mjtrac/test.jks
  springboot:
    name: MyCamel

    # keep Camel running
    main-run-controller: true

    dump-routes: true
    #routes-reload-enabled: true
    #routes-reload-directory: src/main/resources/forwardroute
    #routes-reload-pattern: classpath:camel/*
    
# which directory(s) to scan for routes/route-configurations which can be xml, yaml or java files
    #routes-include-pattern: classpath:myroutes/*
    #routes-include-pattern: classpath:forwardroute/*
    #routes-include-pattern: classpath:sslroute/*
    routes-include-pattern: classpath:ssl2/*
    #,classpath:myroutes/*

mllp:
  inbound:
    port: 15679
  outbound:
    port: 15678

server:
  port: 8080
