logging:
  level:
    root: INFO
    org.apache.camel.component.mllp: DEBUG
  file:
    name: logs/mitchconnect.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    console: "" # Console logging disabled
    
management:
  endpoints:
    web:
      exposure:
        include:
          - "prometheus"
          - "camelroutes"
          - "metrics"
    metrics:
      enabled: true

server:
  port: 8080

spring:
  boot:
    run:
      #jvmArguments: -Djavax.net.debug=ssl,handshake,certpath
  dataSource:
    url: jdbc:sqlite:mydata.db
    driver-class-name: org.sqlite.JDBC
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    mode: "HTML"
    encoding: "UTF-8"
    

camel:
  main:
    routes-builder-loader-ignore-loading-error: false
  mllp:
    # These ports are used in the MllpNoSslReceive and MllpNoSslSend routes
    # defined in src/main/resources/ssl2does mllpReceive use
    no_ssl:
      inbound-port: 15681
      inbound-host: "0.0.0.0"
      outbound-port: 15682
      outbound-host: "0.0.0.0"
    ssl:
      # These ports and resources are used in the channel
      # MllpSSLForwardingRoute,
      # defined in src/main/routes/ssl2/yamlMllpSslRoute.yaml
      keystore:
        resource: "classpath:test.jks"
        password: password
        keypassword: password
      truststore:
        resource: "classpath:truststore.jks"
        password: password
      inbound:
        port: 15679
        host: "0.0.0.0"
      outbound:
        port: 15678
        host: "0.0.0.0"
    nextchannel:
      # These ports and hosts can be referenced
      # in your next channel
      inbound:
        host: TBD
        port: TBD
      outbound:
        host: TBD
        port: TBD
      
  management:
    enabled: true
    jmxAgent: true
    jmx:
      statistic-enabled: true
      statistics-enabled: true
  micrometer:
    enabled: false #true
    route-metrics: false #true

#  netty:
#    ssl:
#      keystore:
#        password: "password"
#        resource: file:/Users/mjtrac/test.jks
  springboot:
    name: MitchConnect

    # keep Camel running
    main-run-controller: true

    dump-routes: true
    #routes-reload-enabled: true
    #routes-reload-directory: src/main/resources/forwardroute
    #routes-reload-pattern: classpath:camel/*
    
# which directory(s) to scan for routes/route-configurations which can be xml, yaml or java files
    #routes-include-pattern: classpath:unloadedroutes/*
    routes-include-pattern: classpath:loadedroutes/**
    #,classpath:myroutes/*


