#logging:
#  level:
#    org.apache.camel.component.mllp: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - "prometheus"
          - "camelroutes"
          - "metrics"
    metrics:
      enabled: true
camel:
  main:
    routes-builder-loader-ignore-loading-error: false
  mllp:
    ssl:
      keystore:
        resource: "classpath:test.jks"
        password: password
        keypassword: password
      truststore:
        resource: "classpath:truststore.jks"
        password: password
# This is used in the channel in src/main/routes/ssl2
      inbound:
        port: 15679
      outbound:
        port: 15678
  management:
    enabled: true
    jmxAgent: true
    jmx:
      statistic-enabled: true
      statistics-enabled: true
#  micrometer:
#    enabled: false #true
#    route-metrics: false #true
#  netty:
#    ssl:
#      keystore:
#        password: "password"
#        resource: file:/Users/mjtrac/test.jks
  springboot:
    name: CamelMllpSslHL7Demo

    # keep Camel running
    main-run-controller: true

    dump-routes: true
    #routes-reload-enabled: true
    #routes-reload-directory: src/main/resources/forwardroute
    #routes-reload-pattern: classpath:camel/*
    
# which directory(s) to scan for routes/route-configurations which can be xml, yaml or java files
    #routes-include-pattern: classpath:myroutes/*
    #routes-include-pattern: classpath:forwardroute/*
    #routes-include-pattern: classpath:sslroute/*
    routes-include-pattern: classpath:ssl2/*
    #,classpath:myroutes/*


server:
  port: 8080

spring:
  boot:
    run:
      jvmArguments: -Djavax.net.debug=ssl,handshake,certpath
  dataSource:
    url: jdbc:sqlite:mydata.db
    driver-class-name: org.sqlite.JDBC
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    mode: "HTML"
    encoding: "UTF-8"
    
